name = "durable-object-counter"
main = "./worker.mjs"
compatibility_date = "2022-05-13"
compatibility_flags = [
    "streams_enable_constructors"
]

[build]
command = "make build"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]