name = "env"
main = "./worker.mjs"
compatibility_date = "2022-05-13"
compatibility_flags = [
    "streams_enable_constructors"
]

[build]
command = "make build"

# declare environment variables and assign values
# https://developers.cloudflare.com/workers/platform/environment-variables/
[vars]
MY_ENV = 'my env value'
